import type { NextConfig } from 'next';
import { wpBlogRedirects } from './lib/wp-blog-redirects';

const securityHeaders = [
  { key: 'X-DNS-Prefetch-Control', value: 'on' },
  { key: 'X-XSS-Protection', value: '1; mode=block' },
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=(), browsing-topics=()',
  },
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload',
  },
  {
    key: 'Content-Security-Policy',
    value: [
      "default-src 'self'",
      "script-src 'self' 'unsafe-inline' https://www.google.com https://www.gstatic.com",
      "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
      "img-src 'self' data: blob: https:",
      "font-src 'self' data: https://fonts.gstatic.com",
      "connect-src 'self' https://api.resend.com https://api.brevo.com https://cdn.sanity.io https://www.google.com https://www.gstatic.com https://recaptcha.google.com",
      "frame-src https://www.google.com https://recaptcha.google.com",
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "frame-ancestors 'none'",
    ].join('; '),
  },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  compress: true,
  // Reduce build memory: skip browser source maps and limit compile workers
  productionBrowserSourceMaps: false,
  experimental: {
    cpus: 1,
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [
      { protocol: 'https', hostname: 'cdn.sanity.io' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: '**' },
    ],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: securityHeaders,
      },
    ];
  },
  async redirects() {
    return [
      // ── 1. WordPress blog posts (auto-generated by `npm run import:blog`) ──
      // Original WP URLs lived at the root (/post-slug/); these 301 to the
      // new canonical /blog/<slug>. Empty until import:blog has run.
      ...wpBlogRedirects,

      // ── 2. Legacy WP slug differences ──
      { source: '/about-us',     destination: '/about',     permanent: true },
      { source: '/contact-us',   destination: '/contact',   permanent: true },

      // ── 3. Old case-studies URL structure → unified /portfolio ──
      { source: '/case-studies',                destination: '/portfolio', permanent: true },
      { source: '/case-studies/:slug*',         destination: '/portfolio', permanent: true },

      // ── 4. Internal /pages prefix some old links use ──
      { source: '/pages/:slug*', destination: '/:slug*',    permanent: true },

      // ── 5. Legacy WP utility URLs that no longer have a home ──
      { source: '/we-are-hiring',      destination: '/careers', permanent: true },
      { source: '/human-resources',    destination: '/careers', permanent: true },
      { source: '/mission-and-vision', destination: '/about',   permanent: true },
      { source: '/thank-you',          destination: '/',        permanent: true },
      { source: '/rssfeed',            destination: '/blog',    permanent: true },

      // ── 6. WP service slugs renamed in the new CMS ──
      // Three are pure renames; five collapse onto the closest existing service page.
      { source: '/services/mobile-app-development',       destination: '/services/mobile-application-development', permanent: true },
      { source: '/services/custom-app-development',       destination: '/services/custom-application-development', permanent: true },
      { source: '/services/devops-service-providers',     destination: '/services/devops-consulting',              permanent: true },
      { source: '/services/cloud-consulting-services',    destination: '/services/cloud-services',                 permanent: true },
      { source: '/services/server-management',            destination: '/services/cloud-managed-services',         permanent: true },
      { source: '/services/24-7-server-administration',   destination: '/services/cloud-managed-services',         permanent: true },
      { source: '/services/azure-consulting-services',    destination: '/services/cloud-services',                 permanent: true },
      { source: '/services/aws-cloud-consulting',         destination: '/services/cloud-services',                 permanent: true },

      // ── 7. Legacy "hire <tech> developers" pages → matching service ──
      // The WP site published these under /technology/hire-<tech>-developers as
      // SEO landing pages. Each maps to the closest existing service slug.
      { source: '/technology/hire-react-developers',          destination: '/services/react-js-development',           permanent: true },
      { source: '/technology/hire-react-native-developers',   destination: '/services/react-native-development',       permanent: true },
      { source: '/technology/hire-ionic-developers',          destination: '/services/ionic-app-development',          permanent: true },
      { source: '/technology/hire-dot-net-developer',         destination: '/services/dot-net-development',            permanent: true },
      { source: '/technology/hire-machine-learning-developers', destination: '/services/hire-machine-learning-developers', permanent: true },
      { source: '/technology/hire-mobile-app-developers',     destination: '/services/mobile-application-development', permanent: true },
      { source: '/technology/hire-android-developers',        destination: '/services/mobile-application-development', permanent: true },
      { source: '/technology/hire-ios-developers',            destination: '/services/mobile-application-development', permanent: true },
      { source: '/technology/hire-devops-engineers',          destination: '/services/devops-consulting',              permanent: true },
      // Catch-all for any remaining /technology/* URLs (mern, mean, full-stack, php, java, node, laravel, blockchain, angular)
      { source: '/technology/:slug*',                         destination: '/services',                                permanent: true },

      // ── 8. Geo-targeted landing pages → relevant service ──
      // The WP site has dozens of /software-development-company-<city> pages.
      // Rather than clone each, send them to the canonical service. Post-launch
      // we can clone individually if SEO traffic warrants it.
      { source: '/software-development-company-:city',        destination: '/services/software-development',           permanent: true },
      { source: '/web-development-company-:city',             destination: '/services/web-development',                permanent: true },
      { source: '/mobile-app-development-company-:city',      destination: '/services/mobile-application-development', permanent: true },

      // ── 9. Other legacy slugs without a Page row ──
      { source: '/legacy-software-modernization',             destination: '/services/software-development',           permanent: true },
      { source: '/sitemap',                                   destination: '/sitemap.xml',                             permanent: false },

      // ── 10. WP author archive pages — collapse onto /blog ──
      { source: '/author/:slug*',                             destination: '/blog',                                    permanent: true },

      // ── 11. /technology hub page (WP page is empty) → /services ──
      { source: '/technology',                                destination: '/services',                                permanent: true },

      // ── 12. WP duplicate homepage slug → real homepage ──
      { source: '/home',                                      destination: '/',                                        permanent: true },
    ];
  },
};

export default nextConfig;
