/**
 * Seed script — replaces all service records with the correct 30 slugs
 * matching the navigation mega menu.
 *
 * Usage:
 *   npx ts-node --compiler-options '{"module":"CommonJS"}' scripts/seed-services.ts
 */

import * as dotenv from 'dotenv'
dotenv.config()

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const DEFAULT_STATS = [
  { value: '700+', label: 'Satisfied Clients' },
  { value: '12+',  label: 'Years of Success' },
  { value: '500+', label: 'Projects Delivered' },
  { value: '3',    label: 'Global Locations' },
]

interface ServiceSeed {
  slug: string
  title: string
  shortDesc: string
  icon: string
  features: string[]
  benefits: string[]
  technologies: string[]
  heroBadge?: string
  heroHighlight?: string
  heroSubtext?: string
  metaTitle: string
  metaDescription: string
  sortOrder: number
}

const SERVICES: ServiceSeed[] = [
  // ── AI & Machine Learning ─────────────────────────────────────────────────
  {
    slug: 'artificial-intelligence',
    title: 'Artificial Intelligence',
    shortDesc: 'End-to-end AI solutions that automate processes, surface insights, and create competitive advantage.',
    icon: 'Brain',
    features: [
      'Machine Learning Model Development',
      'Natural Language Processing',
      'Computer Vision',
      'Predictive Analytics',
      'AI Strategy & Consulting',
      'Model Deployment & MLOps',
    ],
    benefits: [
      'Automate repetitive tasks and reduce operational costs',
      'Make faster, data-driven decisions with predictive insights',
      'Improve customer experience with intelligent personalisation',
      'Scale AI capabilities across your entire organisation',
    ],
    technologies: ['Python', 'TensorFlow', 'PyTorch', 'OpenAI', 'Hugging Face', 'AWS SageMaker', 'Azure ML'],
    heroBadge: 'AI & Machine Learning',
    heroHighlight: 'Artificial Intelligence',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Artificial Intelligence Services | Orion eSolutions',
    metaDescription: 'Expert AI development services — machine learning, NLP, computer vision, and predictive analytics to transform your business.',
    sortOrder: 1,
  },
  {
    slug: 'ai-development',
    title: 'AI Development',
    shortDesc: 'Custom AI application development tailored to your specific business challenges and goals.',
    icon: 'Cpu',
    features: [
      'Custom AI Application Development',
      'AI Integration with Existing Systems',
      'Intelligent Automation',
      'AI-Powered Chatbots',
      'Recommendation Engines',
      'Fraud Detection Systems',
    ],
    benefits: [
      'Purpose-built AI solutions aligned to your workflows',
      'Seamless integration with legacy and modern systems',
      'Faster time-to-value with agile AI delivery',
      'Scalable architectures that grow with your data',
    ],
    technologies: ['Python', 'FastAPI', 'LangChain', 'OpenAI GPT', 'Azure OpenAI', 'Docker', 'Kubernetes'],
    heroBadge: 'AI Development',
    heroHighlight: 'AI Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'AI Development Services | Orion eSolutions',
    metaDescription: 'Custom AI application development services. Build intelligent solutions with machine learning, NLP, and automation.',
    sortOrder: 2,
  },
  {
    slug: 'generative-ai-development',
    title: 'Generative AI Development',
    shortDesc: 'Harness the power of generative AI — from content generation to code assistance and beyond.',
    icon: 'Sparkles',
    features: [
      'LLM Fine-Tuning & Prompt Engineering',
      'RAG (Retrieval-Augmented Generation)',
      'AI Content Generation Platforms',
      'Code Generation Tools',
      'Image & Video AI Generation',
      'Enterprise GenAI Integration',
    ],
    benefits: [
      'Accelerate content creation at scale',
      'Automate knowledge work with intelligent language models',
      'Reduce development cycles with AI-assisted coding',
      'Create differentiated products powered by generative AI',
    ],
    technologies: ['GPT-4', 'Claude', 'Gemini', 'Stable Diffusion', 'LangChain', 'Pinecone', 'Weaviate'],
    heroBadge: 'Generative AI',
    heroHighlight: 'Generative AI Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Generative AI Development Services | Orion eSolutions',
    metaDescription: 'Expert generative AI development — LLM fine-tuning, RAG pipelines, AI content platforms, and enterprise GenAI integration.',
    sortOrder: 3,
  },
  {
    slug: 'llm-development',
    title: 'LLM Development',
    shortDesc: 'Build and deploy large language model solutions that understand, generate, and act on natural language.',
    icon: 'MessageSquare',
    features: [
      'Custom LLM Training & Fine-Tuning',
      'LLM API Integration',
      'Prompt Engineering & Optimisation',
      'Conversational AI Platforms',
      'Document Intelligence',
      'LLM Evaluation & Safety',
    ],
    benefits: [
      'Tailor language models to your domain and vocabulary',
      'Build reliable conversational experiences at scale',
      'Reduce hallucinations with robust evaluation pipelines',
      'Maintain data privacy with on-premise LLM options',
    ],
    technologies: ['Llama', 'Mistral', 'OpenAI', 'Anthropic Claude', 'Hugging Face', 'vLLM', 'ONNX'],
    heroBadge: 'LLM Development',
    heroHighlight: 'LLM Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'LLM Development Services | Orion eSolutions',
    metaDescription: 'Custom large language model development — fine-tuning, RAG, conversational AI, and enterprise LLM deployment.',
    sortOrder: 4,
  },
  {
    slug: 'hire-machine-learning-developers',
    title: 'Hire Machine Learning Developers',
    shortDesc: 'Augment your team with expert ML engineers who deliver production-ready models and pipelines.',
    icon: 'UserCheck',
    features: [
      'Dedicated ML Engineers',
      'Team Augmentation',
      'Model Development & Training',
      'MLOps & Pipeline Automation',
      'Data Engineering Support',
      'Flexible Engagement Models',
    ],
    benefits: [
      'Access senior ML talent without lengthy recruitment',
      'Scale your AI team up or down as project needs change',
      'Accelerate delivery with proven ML practitioners',
      'Reduce hiring risk with vetted, experienced engineers',
    ],
    technologies: ['Python', 'scikit-learn', 'TensorFlow', 'PyTorch', 'MLflow', 'Airflow', 'Spark'],
    heroBadge: 'Staff Augmentation',
    heroHighlight: 'Machine Learning Developers',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Hire Machine Learning Developers | Orion eSolutions',
    metaDescription: 'Hire expert machine learning developers on demand. Flexible engagement models, dedicated ML engineers, and proven delivery.',
    sortOrder: 5,
  },
  {
    slug: 'nlp-services',
    title: 'NLP Services',
    shortDesc: 'Natural language processing solutions that transform unstructured text into actionable intelligence.',
    icon: 'AlignLeft',
    features: [
      'Text Classification & Sentiment Analysis',
      'Named Entity Recognition',
      'Information Extraction',
      'Language Translation',
      'Text Summarisation',
      'Chatbot & Virtual Assistant Development',
    ],
    benefits: [
      'Extract structured insights from unstructured text at scale',
      'Understand customer sentiment across every channel',
      'Automate document processing and data extraction',
      'Build multilingual experiences for global audiences',
    ],
    technologies: ['spaCy', 'NLTK', 'Transformers', 'BERT', 'GPT', 'OpenNLP', 'Stanford NLP'],
    heroBadge: 'Natural Language Processing',
    heroHighlight: 'NLP Services',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'NLP Services | Natural Language Processing | Orion eSolutions',
    metaDescription: 'Enterprise NLP services — sentiment analysis, entity recognition, text classification, and conversational AI solutions.',
    sortOrder: 6,
  },
  {
    slug: 'ai-consulting',
    title: 'AI Consulting',
    shortDesc: 'Strategic AI advisory to help you identify opportunities, define roadmaps, and deliver measurable ROI.',
    icon: 'Lightbulb',
    features: [
      'AI Opportunity Assessment',
      'AI Strategy & Roadmap',
      'Use-Case Prioritisation',
      'Data Readiness Assessment',
      'Vendor & Platform Evaluation',
      'AI Governance & Ethics',
    ],
    benefits: [
      'Avoid costly missteps with expert strategic guidance',
      'Prioritise high-ROI AI initiatives first',
      'Build internal AI capability and culture',
      'Ensure responsible AI adoption with governance frameworks',
    ],
    technologies: ['Azure AI', 'AWS AI Services', 'Google Cloud AI', 'DataRobot', 'Vertex AI'],
    heroBadge: 'AI Strategy',
    heroHighlight: 'AI Consulting',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'AI Consulting Services | Orion eSolutions',
    metaDescription: 'Expert AI consulting to define your strategy, assess AI readiness, and deliver measurable business outcomes.',
    sortOrder: 7,
  },

  // ── Software Development ────────────────────────────────────────────────────
  {
    slug: 'application-development',
    title: 'Application Development',
    shortDesc: 'Full-cycle application development — from discovery and design to deployment and ongoing support.',
    icon: 'Code2',
    features: [
      'Web Application Development',
      'Mobile Application Development',
      'Enterprise Application Development',
      'API Development & Integration',
      'UI/UX Design',
      'Quality Assurance & Testing',
    ],
    benefits: [
      'Deliver reliable, scalable applications on time and budget',
      'User-centric design that drives adoption',
      'Robust architecture built for future growth',
      'Continuous delivery with agile development practices',
    ],
    technologies: ['React', 'Next.js', 'Node.js', '.NET', 'Java', 'Flutter', 'React Native'],
    heroBadge: 'Application Development',
    heroHighlight: 'Application Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Application Development Services | Orion eSolutions',
    metaDescription: 'End-to-end application development services — web, mobile, and enterprise apps built with modern technologies.',
    sortOrder: 8,
  },
  {
    slug: 'software-development',
    title: 'Software Development',
    shortDesc: 'Bespoke software solutions engineered to solve your unique business challenges at any scale.',
    icon: 'Terminal',
    features: [
      'Custom Software Development',
      'SaaS Product Development',
      'Legacy System Modernisation',
      'Software Architecture Design',
      'Agile Development & Scrum',
      'DevOps Integration',
    ],
    benefits: [
      'Purpose-built software that fits your exact requirements',
      'Faster time-to-market with agile delivery',
      'Reduce technical debt with clean, maintainable code',
      'Long-term partnership for continuous improvement',
    ],
    technologies: ['Python', 'Java', 'C#', '.NET', 'Node.js', 'Go', 'PHP'],
    heroBadge: 'Software Development',
    heroHighlight: 'Software Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Software Development Services | Orion eSolutions',
    metaDescription: 'Custom software development company with 12+ years experience. Bespoke solutions for startups and enterprises.',
    sortOrder: 9,
  },
  {
    slug: 'custom-application-development',
    title: 'Custom Application Development',
    shortDesc: 'Tailor-made applications designed from the ground up to meet your specific business requirements.',
    icon: 'Layers',
    features: [
      'Business Process Automation',
      'Custom Workflow Engines',
      'Multi-Tenant SaaS Platforms',
      'Third-Party API Integration',
      'Real-Time Data Processing',
      'Custom Reporting & Dashboards',
    ],
    benefits: [
      'Eliminate off-the-shelf limitations with purpose-built software',
      'Own your IP and reduce licensing costs',
      'Integrate seamlessly with existing tools and data',
      'Scale features in line with your business growth',
    ],
    technologies: ['React', 'Vue.js', 'Node.js', 'Django', 'Laravel', 'PostgreSQL', 'MongoDB'],
    heroBadge: 'Custom Development',
    heroHighlight: 'Custom Application Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Custom Application Development | Orion eSolutions',
    metaDescription: 'Custom application development services tailored to your business. Build scalable, secure, and feature-rich applications.',
    sortOrder: 10,
  },
  {
    slug: 'web-development',
    title: 'Web Development',
    shortDesc: 'High-performance websites and web applications that engage users and drive business results.',
    icon: 'Globe',
    features: [
      'Corporate Website Development',
      'E-Commerce Development',
      'Progressive Web Apps (PWA)',
      'CMS Development & Integration',
      'Performance Optimisation',
      'Responsive & Accessible Design',
    ],
    benefits: [
      'Fast, SEO-friendly websites that rank and convert',
      'Exceptional user experiences across all devices',
      'Secure, scalable infrastructure with 99.9% uptime',
      'CMS-powered sites you can manage without developers',
    ],
    technologies: ['Next.js', 'React', 'WordPress', 'Shopify', 'Tailwind CSS', 'TypeScript', 'Vercel'],
    heroBadge: 'Web Development',
    heroHighlight: 'Web Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Web Development Company | Orion eSolutions',
    metaDescription: 'Professional web development services — corporate websites, e-commerce, PWAs, and CMS platforms built for performance.',
    sortOrder: 11,
  },
  {
    slug: 'mobile-application-development',
    title: 'Mobile Application Development',
    shortDesc: 'Native and cross-platform mobile apps that deliver seamless experiences on iOS and Android.',
    icon: 'Smartphone',
    features: [
      'iOS App Development',
      'Android App Development',
      'Cross-Platform Development',
      'App UI/UX Design',
      'App Store Optimisation',
      'Mobile Backend & API Development',
    ],
    benefits: [
      'Reach customers on the devices they use most',
      'Cut development costs with cross-platform approaches',
      'High-performance apps with native-like experiences',
      'Ongoing maintenance and feature roadmap support',
    ],
    technologies: ['React Native', 'Flutter', 'Swift', 'Kotlin', 'Expo', 'Firebase', 'GraphQL'],
    heroBadge: 'Mobile Development',
    heroHighlight: 'Mobile Application Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Mobile Application Development | Orion eSolutions',
    metaDescription: 'iOS and Android mobile app development services. Native and cross-platform apps for startups and enterprises.',
    sortOrder: 12,
  },
  {
    slug: 'it-staff-augmentation',
    title: 'IT Staff Augmentation',
    shortDesc: 'Extend your engineering team with vetted IT professionals exactly when and where you need them.',
    icon: 'Users',
    features: [
      'Dedicated Development Teams',
      'Individual Developer Augmentation',
      'Short & Long-Term Engagements',
      'Technical Screening & Vetting',
      'Seamless Team Integration',
      'Flexible Scaling Up / Down',
    ],
    benefits: [
      'Access global talent without recruitment overhead',
      'Start in days, not months',
      'Full transparency and direct communication',
      'Reduce risk with flexible contract terms',
    ],
    technologies: ['React', 'Node.js', 'Python', 'Java', '.NET', 'AWS', 'DevOps'],
    heroBadge: 'Staff Augmentation',
    heroHighlight: 'IT Staff Augmentation',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'IT Staff Augmentation Services | Orion eSolutions',
    metaDescription: 'Scale your tech team fast with IT staff augmentation. Vetted developers, flexible engagements, and seamless integration.',
    sortOrder: 13,
  },
  {
    slug: 'qa-services',
    title: 'QA & Testing Services',
    shortDesc: 'Comprehensive quality assurance to ensure your software is reliable, secure, and performs at its best.',
    icon: 'ShieldCheck',
    features: [
      'Manual & Automated Testing',
      'Performance & Load Testing',
      'Security Testing',
      'Mobile App Testing',
      'API Testing',
      'Regression & Smoke Testing',
    ],
    benefits: [
      'Ship with confidence — catch bugs before users do',
      'Reduce post-release defects and support costs',
      'Accelerate delivery with automated test suites',
      'Protect your brand with rigorous security testing',
    ],
    technologies: ['Selenium', 'Cypress', 'Playwright', 'JMeter', 'Postman', 'Jest', 'Appium'],
    heroBadge: 'Quality Assurance',
    heroHighlight: 'QA & Testing Services',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'QA & Software Testing Services | Orion eSolutions',
    metaDescription: 'End-to-end QA and software testing services — manual, automated, performance, and security testing for web and mobile.',
    sortOrder: 14,
  },

  // ── Enterprise & Cloud ──────────────────────────────────────────────────────
  {
    slug: 'technology-development',
    title: 'Technology Development',
    shortDesc: 'Innovative technology solutions that modernise your operations and create sustainable competitive advantage.',
    icon: 'Zap',
    features: [
      'Digital Product Development',
      'Platform Architecture & Design',
      'System Integration',
      'Technology Modernisation',
      'Proof of Concept Development',
      'Technical Due Diligence',
    ],
    benefits: [
      'Transform ideas into scalable technology products',
      'Modernise legacy systems without business disruption',
      'Align technology investment to business outcomes',
      'Accelerate innovation with experienced engineers',
    ],
    technologies: ['Cloud Platforms', 'Microservices', 'Containerisation', 'Event-Driven Architecture', 'GraphQL'],
    heroBadge: 'Technology Solutions',
    heroHighlight: 'Technology Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Technology Development Services | Orion eSolutions',
    metaDescription: 'Expert technology development services — digital products, platform architecture, and modernisation for enterprises.',
    sortOrder: 15,
  },
  {
    slug: 'erp-development',
    title: 'ERP Development',
    shortDesc: 'Custom ERP solutions that unify your business operations, data, and processes on a single platform.',
    icon: 'LayoutGrid',
    features: [
      'Custom ERP Development',
      'ERP Integration & Migration',
      'Module Development (Finance, HR, Inventory)',
      'ERP Customisation & Extension',
      'Business Intelligence Integration',
      'ERP Support & Maintenance',
    ],
    benefits: [
      'Single source of truth for all business data',
      'Eliminate data silos and manual reconciliation',
      'Real-time visibility into every business function',
      'Scalable ERP that grows with your organisation',
    ],
    technologies: ['SAP', 'Oracle', 'Microsoft Dynamics', 'Odoo', 'NetSuite', '.NET', 'React'],
    heroBadge: 'ERP Solutions',
    heroHighlight: 'ERP Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'ERP Development Services | Orion eSolutions',
    metaDescription: 'Custom ERP development and integration services. Unify your operations with tailored enterprise resource planning solutions.',
    sortOrder: 16,
  },
  {
    slug: 'devops-consulting',
    title: 'DevOps Consulting',
    shortDesc: 'Accelerate software delivery and improve reliability with expert DevOps practices and tooling.',
    icon: 'GitBranch',
    features: [
      'CI/CD Pipeline Setup & Optimisation',
      'Infrastructure as Code',
      'Kubernetes & Container Orchestration',
      'Monitoring & Observability',
      'Security DevOps (DevSecOps)',
      'Cloud Cost Optimisation',
    ],
    benefits: [
      'Deploy faster and more frequently with less risk',
      'Improve system reliability and reduce downtime',
      'Automate infrastructure provisioning and scaling',
      'Gain full visibility into system performance',
    ],
    technologies: ['Kubernetes', 'Docker', 'Terraform', 'Jenkins', 'GitHub Actions', 'Prometheus', 'Grafana'],
    heroBadge: 'DevOps',
    heroHighlight: 'DevOps Consulting',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'DevOps Consulting Services | Orion eSolutions',
    metaDescription: 'Expert DevOps consulting — CI/CD pipelines, Kubernetes, IaC, and DevSecOps to accelerate software delivery.',
    sortOrder: 17,
  },
  {
    slug: 'cloud-services',
    title: 'Cloud Services',
    shortDesc: 'End-to-end cloud services to help you build, migrate, manage, and optimise your cloud environment.',
    icon: 'Cloud',
    features: [
      'Cloud Strategy & Assessment',
      'Cloud Infrastructure Design',
      'Multi-Cloud & Hybrid Cloud',
      'Cloud Security',
      'Cost Management & Optimisation',
      '24×7 Cloud Monitoring',
    ],
    benefits: [
      'Reduce infrastructure costs by up to 40%',
      'Increase agility and deployment speed',
      'Enterprise-grade security and compliance',
      'Scalable infrastructure that matches demand',
    ],
    technologies: ['AWS', 'Microsoft Azure', 'Google Cloud', 'Terraform', 'Ansible', 'Kubernetes'],
    heroBadge: 'Cloud Services',
    heroHighlight: 'Cloud Services',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Cloud Services | Orion eSolutions',
    metaDescription: 'Comprehensive cloud services — strategy, migration, management, and optimisation across AWS, Azure, and GCP.',
    sortOrder: 18,
  },
  {
    slug: 'cloud-managed-services',
    title: 'Cloud Managed Services',
    shortDesc: 'Fully managed cloud operations so your team can focus on innovation instead of infrastructure.',
    icon: 'ServerCog',
    features: [
      '24×7 Cloud Infrastructure Monitoring',
      'Patch Management & Updates',
      'Backup & Disaster Recovery',
      'Performance Optimisation',
      'Security & Compliance Management',
      'Incident Response & Support',
    ],
    benefits: [
      'Eliminate infrastructure management burden',
      'Guaranteed SLAs with 24×7 expert support',
      'Proactive issue resolution before impact',
      'Predictable monthly costs with no surprises',
    ],
    technologies: ['AWS', 'Azure', 'GCP', 'CloudWatch', 'Azure Monitor', 'Datadog', 'PagerDuty'],
    heroBadge: 'Managed Cloud',
    heroHighlight: 'Cloud Managed Services',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Cloud Managed Services | Orion eSolutions',
    metaDescription: 'Fully managed cloud services with 24×7 monitoring, support, and optimisation. Let experts run your cloud infrastructure.',
    sortOrder: 19,
  },
  {
    slug: 'cloud-migration-services',
    title: 'Cloud Migration Services',
    shortDesc: 'Seamless, risk-free cloud migration that moves your workloads to the cloud without disruption.',
    icon: 'CloudUpload',
    features: [
      'Cloud Readiness Assessment',
      'Migration Strategy & Planning',
      'Lift-and-Shift Migration',
      'Application Re-Architecture',
      'Data Migration & Validation',
      'Post-Migration Optimisation',
    ],
    benefits: [
      'Migrate with confidence using proven methodologies',
      'Minimise downtime and business disruption',
      'Reduce on-premise infrastructure costs',
      'Unlock cloud-native capabilities after migration',
    ],
    technologies: ['AWS Migration Hub', 'Azure Migrate', 'CloudEndure', 'Terraform', 'Ansible'],
    heroBadge: 'Cloud Migration',
    heroHighlight: 'Cloud Migration Services',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Cloud Migration Services | Orion eSolutions',
    metaDescription: 'Expert cloud migration services — risk-free migration planning, execution, and optimisation for any workload.',
    sortOrder: 20,
  },
  {
    slug: 'crm-development',
    title: 'CRM Development',
    shortDesc: 'Custom CRM solutions that help you manage customer relationships, sales pipelines, and growth.',
    icon: 'HeartHandshake',
    features: [
      'Custom CRM Development',
      'CRM Integration & Migration',
      'Sales Pipeline Automation',
      'Customer 360 Dashboards',
      'Marketing Automation Integration',
      'CRM Mobile Apps',
    ],
    benefits: [
      'Centralise all customer data in one platform',
      'Increase sales team productivity with automation',
      'Improve customer retention with better insights',
      'Scale CRM capabilities as your business grows',
    ],
    technologies: ['Salesforce', 'HubSpot', 'Zoho', 'Microsoft Dynamics CRM', 'React', 'Node.js'],
    heroBadge: 'CRM Solutions',
    heroHighlight: 'CRM Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'CRM Development Services | Orion eSolutions',
    metaDescription: 'Custom CRM development and integration services. Build, customise, or migrate your CRM to drive sales and retention.',
    sortOrder: 21,
  },
  {
    slug: 'cybersecurity',
    title: 'Cybersecurity',
    shortDesc: 'Protect your business, data, and reputation with comprehensive cybersecurity services.',
    icon: 'ShieldAlert',
    features: [
      'Penetration Testing & Vulnerability Assessment',
      'Security Architecture Design',
      'Managed Security Operations (SOC)',
      'Compliance & Risk Management',
      'Incident Response',
      'Security Awareness Training',
    ],
    benefits: [
      'Identify and remediate vulnerabilities before attackers do',
      'Meet regulatory compliance requirements (ISO 27001, GDPR)',
      'Reduce risk of costly data breaches',
      '24×7 threat detection and rapid incident response',
    ],
    technologies: ['SIEM', 'EDR', 'OWASP', 'ISO 27001', 'NIST', 'Splunk', 'CrowdStrike'],
    heroBadge: 'Cybersecurity',
    heroHighlight: 'Cybersecurity',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Cybersecurity Services | Orion eSolutions',
    metaDescription: 'Comprehensive cybersecurity services — penetration testing, SOC, compliance, and incident response to protect your business.',
    sortOrder: 22,
  },
  {
    slug: 'managed-it-services',
    title: 'Managed IT Services',
    shortDesc: 'Proactive, end-to-end IT management that keeps your systems running, secure, and optimised.',
    icon: 'Monitor',
    features: [
      '24×7 IT Helpdesk & Support',
      'Network Management & Monitoring',
      'Hardware & Software Management',
      'IT Security Management',
      'Backup & Business Continuity',
      'Vendor Management',
    ],
    benefits: [
      'Predictable IT costs with a fixed monthly fee',
      'Proactive maintenance reduces costly downtime',
      'Access an entire IT department for less',
      'Focus on core business while we handle IT',
    ],
    technologies: ['Microsoft 365', 'Azure', 'AWS', 'Intune', 'ServiceNow', 'Zabbix'],
    heroBadge: 'Managed IT',
    heroHighlight: 'Managed IT Services',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Managed IT Services | Orion eSolutions',
    metaDescription: 'End-to-end managed IT services with 24×7 support, proactive monitoring, and expert management for your IT infrastructure.',
    sortOrder: 23,
  },

  // ── Technology Specialisms ─────────────────────────────────────────────────
  {
    slug: 'react-js-development',
    title: 'React.js Development',
    shortDesc: 'Scalable, high-performance React.js applications built by experienced frontend engineers.',
    icon: 'Atom',
    features: [
      'React SPA & Progressive Web Apps',
      'Next.js Full-Stack Development',
      'React Component Library Development',
      'Performance Optimisation',
      'State Management (Redux, Zustand)',
      'React Testing & QA',
    ],
    benefits: [
      'Fast, interactive UIs that delight users',
      'Component-driven architecture for easy maintenance',
      'SEO-friendly with server-side rendering',
      'Large ecosystem with long-term community support',
    ],
    technologies: ['React', 'Next.js', 'TypeScript', 'Redux', 'Tailwind CSS', 'Vite', 'Jest'],
    heroBadge: 'React.js',
    heroHighlight: 'React.js Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'React.js Development Services | Orion eSolutions',
    metaDescription: 'Expert React.js development services — SPAs, Next.js apps, component libraries, and performance optimisation.',
    sortOrder: 24,
  },
  {
    slug: 'react-native-development',
    title: 'React Native Development',
    shortDesc: 'Cross-platform mobile apps with React Native that look and feel truly native on iOS and Android.',
    icon: 'Smartphone',
    features: [
      'iOS & Android App Development',
      'Cross-Platform Code Sharing',
      'Native Module Integration',
      'Push Notifications & Deep Linking',
      'Offline-First Architecture',
      'App Performance Optimisation',
    ],
    benefits: [
      'One codebase for iOS and Android — faster delivery',
      'Native performance and platform-specific UX',
      'Reduce time-to-market and development costs',
      'Leverage existing React knowledge and libraries',
    ],
    technologies: ['React Native', 'Expo', 'TypeScript', 'Redux', 'Firebase', 'React Navigation'],
    heroBadge: 'React Native',
    heroHighlight: 'React Native Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'React Native Development Services | Orion eSolutions',
    metaDescription: 'Cross-platform React Native mobile app development for iOS and Android. Fast delivery, native performance.',
    sortOrder: 25,
  },
  {
    slug: 'ionic-app-development',
    title: 'Ionic App Development',
    shortDesc: 'Build powerful cross-platform mobile and progressive web apps with Ionic and web technologies.',
    icon: 'Layers',
    features: [
      'Ionic Cross-Platform App Development',
      'Progressive Web Apps (PWA)',
      'Capacitor Native Integration',
      'Ionic + Angular / React / Vue',
      'App Deployment to App Stores',
      'Migration from Cordova to Capacitor',
    ],
    benefits: [
      'One app for web, iOS, and Android',
      'Leverage web developer expertise for mobile',
      'Access native device features via Capacitor',
      'Rapid development with pre-built UI components',
    ],
    technologies: ['Ionic', 'Capacitor', 'Angular', 'React', 'Vue.js', 'TypeScript', 'Cordova'],
    heroBadge: 'Ionic',
    heroHighlight: 'Ionic App Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Ionic App Development Services | Orion eSolutions',
    metaDescription: 'Expert Ionic app development for cross-platform mobile and PWA. iOS, Android, and web from a single codebase.',
    sortOrder: 26,
  },
  {
    slug: 'dot-net-development',
    title: '.NET Development',
    shortDesc: 'Enterprise-grade .NET applications and APIs built with Microsoft technologies for any scale.',
    icon: 'Code',
    features: [
      'ASP.NET Core Web Development',
      '.NET API Development',
      'Blazor Application Development',
      'Azure Integration',
      'Legacy .NET Migration',
      '.NET Microservices',
    ],
    benefits: [
      'Robust, high-performance enterprise applications',
      'Strong typing and reliability with C#',
      'Seamless integration with Microsoft 365 and Azure',
      'Long-term Microsoft support and ecosystem',
    ],
    technologies: ['C#', 'ASP.NET Core', '.NET 8', 'Blazor', 'Entity Framework', 'Azure', 'SQL Server'],
    heroBadge: '.NET',
    heroHighlight: '.NET Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: '.NET Development Services | Orion eSolutions',
    metaDescription: 'Expert .NET development services — ASP.NET Core, APIs, Blazor, and Azure solutions for enterprise applications.',
    sortOrder: 27,
  },
  {
    slug: 'codeigniter-development',
    title: 'CodeIgniter Development',
    shortDesc: 'Fast, lightweight PHP web applications and APIs built with the CodeIgniter framework.',
    icon: 'Flame',
    features: [
      'CodeIgniter Web Application Development',
      'REST API Development',
      'CodeIgniter CMS Development',
      'Performance Optimisation',
      'Legacy CodeIgniter Upgrade',
      'Third-Party Integration',
    ],
    benefits: [
      'Lightweight framework for fast, efficient applications',
      'Rapid development with minimal configuration',
      'Excellent performance on shared hosting environments',
      'Easy to extend and maintain',
    ],
    technologies: ['CodeIgniter 4', 'PHP 8', 'MySQL', 'REST APIs', 'jQuery', 'Bootstrap', 'Redis'],
    heroBadge: 'CodeIgniter',
    heroHighlight: 'CodeIgniter Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'CodeIgniter Development Services | Orion eSolutions',
    metaDescription: 'Expert CodeIgniter PHP development services — web apps, REST APIs, and CMS solutions built for performance.',
    sortOrder: 28,
  },
  {
    slug: 'api-web-services',
    title: 'API & Web Services',
    shortDesc: 'Design, build, and integrate scalable APIs and web services that connect your digital ecosystem.',
    icon: 'Plug',
    features: [
      'RESTful API Development',
      'GraphQL API Development',
      'API Integration & Middleware',
      'API Documentation (OpenAPI/Swagger)',
      'API Security & Authentication',
      'Webhooks & Event-Driven APIs',
    ],
    benefits: [
      'Connect disparate systems and data sources seamlessly',
      'Enable third-party integrations and partnerships',
      'Improve developer experience with well-designed APIs',
      'Scale API infrastructure to handle high traffic',
    ],
    technologies: ['REST', 'GraphQL', 'OpenAPI', 'Node.js', 'FastAPI', 'Kong', 'AWS API Gateway'],
    heroBadge: 'API Development',
    heroHighlight: 'API & Web Services',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'API & Web Services Development | Orion eSolutions',
    metaDescription: 'Expert API and web services development — REST, GraphQL, integrations, and API management at any scale.',
    sortOrder: 29,
  },
  {
    slug: 'zend-web-development',
    title: 'Zend / Laminas Development',
    shortDesc: 'Enterprise PHP web applications built with the Zend Framework (Laminas) for reliability and scale.',
    icon: 'Server',
    features: [
      'Zend Framework / Laminas Development',
      'Enterprise PHP Application Development',
      'Zend Application Migration',
      'Module & Component Development',
      'API & Web Service Development',
      'Performance Tuning & Optimisation',
    ],
    benefits: [
      'Enterprise-grade PHP architecture for complex applications',
      'Component-based design for maintainability',
      'Strong community and long-term support',
      'High performance under heavy load',
    ],
    technologies: ['Laminas', 'Zend Framework', 'PHP 8', 'MySQL', 'PostgreSQL', 'Redis', 'Docker'],
    heroBadge: 'Zend / Laminas',
    heroHighlight: 'Zend Web Development',
    heroSubtext: '12+ Years | Diverse Expertise | 24×7 Support',
    metaTitle: 'Zend / Laminas Web Development | Orion eSolutions',
    metaDescription: 'Expert Zend Framework and Laminas development services for enterprise PHP applications and APIs.',
    sortOrder: 30,
  },
]

async function main() {
  console.log('🗑️  Deleting all existing service records…')
  const deleted = await prisma.service.deleteMany()
  console.log(`   Deleted ${deleted.count} records.`)

  console.log(`\n🌱 Seeding ${SERVICES.length} services…`)

  for (const s of SERVICES) {
    await prisma.service.create({
      data: {
        slug:            s.slug,
        title:           s.title,
        shortDesc:       s.shortDesc,
        description:     '',
        icon:            s.icon,
        features:        s.features,
        benefits:        s.benefits,
        technologies:    s.technologies,
        heroBadge:       s.heroBadge ?? null,
        heroHighlight:   s.heroHighlight ?? null,
        heroSubtext:     s.heroSubtext ?? null,
        heroImageUrl:    null,
        heroStats:       DEFAULT_STATS,
        metaTitle:       s.metaTitle,
        metaDescription: s.metaDescription,
        published:       true,
        sortOrder:       s.sortOrder,
      },
    })
    console.log(`   ✔  ${s.slug}`)
  }

  console.log(`\n✅ Done — ${SERVICES.length} services seeded.`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
