- name: SSH into Server & Deploy
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.SSH_HOST }}
    username: root
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    port: 22
    timeout: 120s
    command_timeout: 20m
    script_stop: true
    script: |
      set -euo pipefail

      APP_DIR="/var/www/web26.customerdemourl.com"

      cd "${APP_DIR}"

      git config --global --add safe.directory ${APP_DIR}

      git pull origin develop

      /root/.nvm/versions/node/v24.15.0/bin/npm i
      /root/.nvm/versions/node/v24.15.0/bin/npm run build
      /root/.nvm/versions/node/v24.15.0/bin/pm2 restart web26.customerdemourl.com
